# Check that there is correct spelling in all files
name: Check spelling

# Check spelling on the 21st day of the month.
# 21st as the first letter of this repo is the 21st letter in the alphabet.
on:
  push:
  pull_request:
  schedule:
  - cron: "0 0 21 * *"


jobs:
  check_spelling:

    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:

      - name: Set up Git repository
        uses: actions/checkout@v4

      - name: delete files that have two languages
        run: |
          rm docs/content/20240614_nicole_teroni/README.md
          rm docs/content/20241108_richel_bilderbeek/README.md
          rm docs/content/20240315_osu/README.md
          rm docs/content/20231208_anna_hallberg/README.md
          rm docs/content/20240112_emmi_puuvuori/README.md
          rm docs/content/20231025_richel_bilderbeek/README.md
          rm docs/content/20231110_adam_gill/README.md
          rm docs/content/20231020_ismail_elouafiq/README.md
          rm docs/content/20240913_paul_jacobson/README.md
          rm docs/content/20240209_douglas_spangler/README.md
          rm docs/content/20230908_martin_johnsson/README.md
          rm docs/publicity/uu_newsletter_20230613/README.md

      - uses: igsekor/pyspelling-any@v1.0.4

